new pr
swecc-uw/swecc-website pull request #105
Opened 2024-09-28 23:35 UTC by RandolphTang

Author: <name>

## What changes were made?

All officer info is updated

## Why are these changes important/necessary?

## (If applicable) Screenshots of your changes. Providing an “old vs. new” comparison would be great!

2024-09-29 01:00 UTC, elimelt requested changes

2024-10-06 13:57 UTC, ShawnCollinge reviewed
Why do we have header.js and nav-bar.js with the same links? I didn't dive too deep into it but something to maybe look into for refactoring.

2024-10-06 13:57 UTC, ShawnCollinge commented on package.json
> +    "resend": "^4.0.0",
is this being used anywhere?

2024-10-06 13:57 UTC, ShawnCollinge commented on src/Components/App.js
> +        <Route path="/join-Now" element={<JoinNow />} />
should probably lowercase the `N` to follow the rest.

2024-10-06 13:57 UTC, ShawnCollinge commented on src/Components/Events.js
> +  const postId = [
Is there a reason for hardcoding postIds? Are we not just wanting the most recent `n` posts? Maybe you can't answer this but maybe @elimelt can?

2024-10-06 13:57 UTC, ShawnCollinge commented on src/Components/Header.js
> +          <NavLink to="/Events" className="nav-link">
Does this link work? You lowercased it in the routes.

2024-10-06 13:57 UTC, ShawnCollinge commented on src/Components/Header.js
> +          <NavLink to="/About" className="nav-link">
ditto here

2024-10-06 13:57 UTC, ShawnCollinge commented on src/Components/Header.js
> +          <NavLink to="/Join-Now" className="join-now-btn nav-link">
ditto here.

2024-10-06 13:57 UTC, ShawnCollinge commented on src/Components/Home.js
> +          url="https://www.instagram.com/p/C7uRAftvEKV/?utm_source=ig_web_copy_link"
Why are we hardcoding these urls?

2024-10-06 13:57 UTC, ShawnCollinge commented on src/Components/Navbar.js
> +            route={"/Officers"}
This should also be lowercase.

2024-10-06 13:57 UTC, ShawnCollinge commented on src/Components/Navbar.js
> +            route={"/Sponsor"}
lowercase?

2024-10-06 13:57 UTC, ShawnCollinge commented on src/Components/Navbar.js
> +          <NavLink to="/Officers" onClick={props.closeExpand}>
lowercase?

2024-10-06 13:57 UTC, ShawnCollinge commented on src/Components/Officers.js
> +              {[2024, 2023, 2022, 2021].map((year) => (
Maybe we can not hardcode years, can check if after september then add the next year? Starting with 2021.

2024-10-06 14:00 UTC, ShawnCollinge commented on react-email-starter/emails/notion-magic-link.tsx
> +const main = {
Why don't we move this css into it's own spot and I think the css can be shared across this and plaid-verify?

2024-10-07 01:40 UTC, ShawnCollinge commented on src/Components/Home.js
> +        onLoad={() => console.log("Loaded!")}
Shouldn't have console.logs in prod please.

2024-10-07 01:44 UTC, closed without merging