Front-Page Title Image Carousel
swecc-uw/swecc-website pull request #88
Opened 2024-04-12 05:54 UTC by RandolphTang

Author: Randolph Jenkins

What changes were made?
Change the home page's title section's background image, and make it into carousel images with components that allow interaction.

Why are these changes important/necessary?
Fixed the mentioned issues in the Issues section, and added dynamics to the web.

(If applicable) Screenshots of your changes. Providing an “old vs. new” comparison would be great!
The main change is in Home.js and Home.css. and also add root and dark mode color variables in index.css

2024-04-12 19:43 UTC, shiinasugioka commented on src/CSS/Home.css
> +  height: 26vw;
since some of the photos are being cut off, can you make this height value slightly bigger

2024-04-12 19:47 UTC, shiinasugioka commented on src/Components/Home.js
> +        const divStyle = {
`divStyle` is a generic name that could lead to confusion. Rename this value to specify what div it is pointing to

2024-04-12 19:50 UTC, shiinasugioka commented on src/Components/Home.js
> +                    <button onClick={prevImg} className="prevImgButton">&lt;</button>
on arrow button clicks, add css transitions to make this smoother. Same for when the 6000 ms are up and the photo in the carousel changes. Any time the photo changes, add a smooth transition with css

2024-04-12 19:54 UTC, shiinasugioka commented on src/Components/Home.js
> +                The Software Engineering Career Club (SWECC) is a student-led organization at the University of
please install the [Prettier code formatter extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) to make the code more neat. If you are using vs code, you can install it from the extensions tab. If you are using Webstorm, this extension is already built in. For any other IDEs, just make sure the code formatter is using Prettier

2024-04-12 19:58 UTC, shiinasugioka requested changes
I left some comments in your code! Overall, great job implementing the carousel. There's a couple styling issues that I want you to fix, but otherwise this looks great! Once the code fixes are in, let me know again and I can review the changes before we merge it.

2024-04-13 08:34 UTC, RandolphTang commented
@shiinasugioka Hello, thank you for those comments, I revised it and all the changes can be found in the commit "[front-page title img background 4/13]." 

Have a good weekend, peace out

2024-04-13 19:39 UTC, shiinasugioka approved these changes

2024-04-13 19:40 UTC, shiinasugioka approved these changes

2024-04-13 19:41 UTC, merged