changed the previous events to same size
swecc-uw/swecc-website pull request #99
Opened 2024-06-20 08:40 UTC by wena04

Author: <Anthony Wen> Discord: wena04

## What changes were made?

Issue 
Made the posts display 3 at a time, and added a prev and next button so it would display the next set of previous events.
Created 2 new files, 1 component for the posts and button and the CSS for that component. However, the state functions for the next and prev buttons still need a bit of fixing. Right now, no matter how you click it it only displays the first 3 posts and not the next set. I will have to figure that part out later on when I have more time. I split the posts part in the home.js into a new component file so that it's easier.

*Don't merge the commented out firebase initialization in index.js* I commented it out so its easier to run on my localhost

## Why are these changes important/necessary?

the sizing for the posts were different, and the events were all over the place. this made it look a bit cleaner.

## (If applicable) Screenshots of your changes. Providing an “old vs. new” comparison would be great!

Before
<img width="1512" alt="Old" src="https://github.com/swecc-uw/swecc-website/assets/152733514/4d48fa56-7652-49bf-91f4-7517d2cc62f4">
After
<img width="1512" alt="New" src="https://github.com/swecc-uw/swecc-website/assets/152733514/12ab06b4-115f-476a-b2fe-eb90cfd0640b">

2024-06-21 01:09 UTC, elimelt requested changes
Looks good for the most part, but try to remove the hard-coded URIs from Home.js by factoring the `postsData` from Posts.js into their own file within the Data directory

2024-06-21 01:09 UTC, elimelt commented on src/Components/Posts.js
> +const postsData = [
I don't love that these are hard-coded, but I also don't really feel like integrating with the instagram API so I'll let it slide...

2024-06-21 01:09 UTC, elimelt commented on src/Components/Home.js
> +          Held in the EAC, these meeting feature topics in a vast number of
Careful touching more code than necessary. Obvious you were just formatting though so it shouldn't matter too much

2024-06-21 01:09 UTC, elimelt commented on src/Components/Home.js
> +        className="instaPost slide-up"
Probably shouldn't have these post uris hard-coded here, especially since we are hard-coding them elsewhere. Try to factor this out somehow?

2024-06-21 01:09 UTC, elimelt commented on src/Components/Home.js
> +      <Posts></Posts>
No child components means you can change this to `<Posts/>`

2024-09-01 03:09 UTC, elimelt commented
@wena04 Are you planning on making changes or should I close the PR?

2024-09-01 03:53 UTC, wena04 commented
> @wena04 Are you planning on making changes or should I close the PR?

@elimelt Yes, I'm planning on working on it still. Do I just submit another pull request to this issue with the changes edited? How should I change things without messing up the current code or anything. I'm kind of new to this pull request thing.

2024-09-01 04:23 UTC, elimelt commented
You can either address the changes and then resolve conflicts, or resolve conflicts and then address the changes. Really up to you. No need for a new PR, just keep working on this branch and it'll update the PR

2024-10-21 01:23 UTC, closed without merging